apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  labels:
    env: prod
    app: mongo
spec:
  replicas: 1  # Changed from 2 to 1 for MySQL
  selector:
    matchLabels:
      env: prod
      app: mongo
  serviceName: mongo-svc  # Should match service name
  template:
    metadata:
      labels:
        env: prod
        app: mongo
    spec:
      containers:
      - name: mongo-container
        image: mongo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 27017